export const projectTexts = [
  {
    id: "dbk",
    label: "DBK",
    description: "Dokumentation for indplacering i brandklasse",
    kontrolplansId: "_KPKR_D_DBK",
    belongsTo: "designTexts",
  },
  {
    id: "itt",
    label: "ITT",
    description: "Dokumentation for indsatstaktisk traditionelt",
    kontrolplansId: "_KPKR_D_ITT",
    belongsTo: "designTexts",
  },
  {
    id: "bsr",
    label: "BSR",
    description: "Dokumentation for brandstrategi rapport",
    kontrolplansId: "_KPKR_D_BSR",
    belongsTo: "designTexts",
  },
  {
    id: "bplan",
    label: "BPLAN",
    description: "Brandplaner og situationsplan",
    kontrolplansId: "_KPKR_D_BPLAN",
    belongsTo: "designTexts",
  },
  {
    id: "pfp",
    label: "PFP",
    description: "Pladsfordelings-, belægnings- og evakueringsplaner",
    kontrolplansId: "_KPKR_D_PFP",
    belongsTo: "designTexts",
  },
  {
    id: "kom",
    label: "KOM",
    description: "Brandteknisk dimensionering",
    kontrolplansId: "_KPKR_D_DIM",
    belongsTo: "designTexts",
  },
  {
    id: "funk",
    label: "FUNK",
    description: "Funktionsbeskrivelse",
    kontrolplansId: "_KPKR_D_FUNK",
    belongsTo: "designTexts",
  },
  {
    id: "kpla",
    label: "KPLA",
    description: "Brandtekniske kontrolplaner",
    kontrolplansId: "_KPKR_D_KPLA",
    belongsTo: "designTexts",
  },
  {
    id: "dkv",
    label: "DKV",
    description: "Drifts-, kontrol-, og vedligeholdelsesplan",
    kontrolplansId: "_KPKR_D_DKV",
    belongsTo: "designTexts",
  },
  {
    id: "flugt",
    label: "FLUGT",
    description: "Flugtvejsgange, -arealer og -trapper.",
    kontrolplansId: "_KPKR_P_FLUGT",
    belongsTo: "flugtvejsData",
  },
  {
    id: "sikt",
    label: "SIKT",
    description: "Sikkerhedstrapper",
    kontrolplansId: "_KPKR_P_SIKT",
    belongsTo: "flugtvejsData",
  },
  {
    id: "red",
    label: "RED",
    description: "Redningsåbninger",
    kontrolplansId: "_KPKR_P_RED",
    belongsTo: "flugtvejsData",
  },
  {
    id: "ind",
    label: "IND",
    description: "Indsatsforhold generelt",
    kontrolplansId: "_KPKR_P_IND",
    belongsTo: "flugtvejsData",
  },
  {
    id: "adsk",
    label: "ADSK",
    description: "Brand- og røgmæssige adskillelser",
    kontrolplansId: "_KPKR_P_ADSK",
    belongsTo: "Bygningsdele",
  },
  {
    id: "dør",
    label: "DØR",
    description: "Brand- flugtvejsdøre",
    kontrolplansId: "_KPKR_P_DØR",
    belongsTo: "Bygningsdele",
  },
  {
    id: "iof",
    label: "IOF",
    description: "Indvendige overflader",
    kontrolplansId: "_KPKR_P_IOF",
    belongsTo: "Bygningsdele",
  },
  {
    id: "uof",
    label: "UOF",
    description: "Udvendige overflader",
    kontrolplansId: "_KPKR_P_UOF",
    belongsTo: "Bygningsdele",
  },
  {
    id: "iso",
    label: "ISO",
    description: "Isoleringsmaterialer",
    kontrolplansId: "_KPKR_P_ISO",
    belongsTo: "Bygningsdele",
  },
  {
    id: "hs",
    label: "HS",
    description: "Røgalarmanlæg",
    kontrolplansId: "_KPKR_P_HS",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "ru",
    label: "RU",
    description: "Vandfyldte slangevinder",
    kontrolplansId: "_KPKR_P_RU",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "raa",
    label: "RAA",
    description: "Stigrør",
    kontrolplansId: "_KPKR_P_RAA",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "vsv",
    label: "VSV",
    description: "Brandsikring af ventilationsanlæg",
    kontrolplansId: "_KPKR_P_VSV",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "stig",
    label: "STIG",
    description: "ABDL-anlæg",
    kontrolplansId: "_KPKR_P_STIG",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "vent",
    label: "VENT",
    description: "Brandtætning af installationsgennemføringer",
    kontrolplansId: "_KPKR_P_VENT",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "abdl",
    label: "ABDL",
    description: "Rør- og kabelinstallationer",
    kontrolplansId: "_KPKR_P_ABDL",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "btæt",
    label: "BTÆT",
    description: "Brandtætning af installationsgennemføringer",
    kontrolplansId: "_KPKR_P_BTÆT",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "rør",
    label: "RØR",
    description: "Rør- og kabelinstallationer",
    kontrolplansId: "_KPKR_P_RØR",
    belongsTo: "Håndslukningsudstyr",
  },
  {
    id: "sys",
    label: "SYS",
    description: "Systemintegrationstest",
    kontrolplansId: "Akkrediteret virksomhed",
    belongsTo: "Funktionsafprøvning",
  },
  {
    id: "aba",
    label: "ABA",
    description: "Automatisk brandalarmanlæg (ABA-anlæg)",
    kontrolplansId: "Akkrediteret virksomhed",
    belongsTo: "Funktionsafprøvning",
  },
  {
    id: "avs",
    label: "AVS",
    description: "Sprinkleranlæg (AVS-anlæg)",
    kontrolplansId: "Akkrediteret virksomhed",
    belongsTo: "Funktionsafprøvning",
  },
  {
    id: "bme",
    label: "BME",
    description: "Brandmandselevator",
    kontrolplansId: "Akkrediteret virksomhed",
    belongsTo: "Funktionsafprøvning",
  },
  {
    id: "abv",
    label: "ABV",
    description: "Automatisk brandventilation (ABV-anlæg)",
    kontrolplansId: "Akkrediteret virksomhed",
    belongsTo: "Funktionsafprøvning",
  },
  {
    id: "f&p",
    label: "F&P",
    description: "Flugtvejs- og panikbelysning",
    kontrolplansId: "Akkrediteret virksomhed",
    belongsTo: "Funktionsafprøvning",
  },
  {
    id: "va",
    label: "VA",
    description: "Varslingsanlæg",
    kontrolplansId: "Akkrediteret virksomhed",
    belongsTo: "Funktionsafprøvning",
  },
  {
    id: "ata",
    label: "ATA",
    description: "Automatisk tryksætningsanlæg (ATA-anlæg)",
    kontrolplansId: "Akkrediteret virksomhed",
    belongsTo: "Funktionsafprøvning",
  },
];
